# Generated by Django 4.1.1 on 2022-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CREATE_TRACKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRACKING_ID', models.CharField(max_length=15)),
                ('ORIGIN', models.CharField(max_length=50)),
                ('DESTINATION', models.CharField(max_length=500)),
                ('SENDER_NAME', models.CharField(max_length=50)),
                ('PHONE', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=50)),
                ('BOOKING_DATE', models.DateField()),
                ('RECIPIENT_NAME', models.CharField(max_length=50)),
                ('RECIPIENT_PHONE', models.CharField(max_length=30)),
                ('RECIPIENT_EMAIL', models.CharField(max_length=50)),
                ('SHIPPING_DATE', models.DateField()),
                ('COURIER', models.CharField(max_length=100)),
                ('CONTENTS', models.CharField(max_length=500)),
                ('QUANTITY', models.CharField(max_length=20)),
                ('WEIGHT', models.CharField(max_length=20)),
                ('STATUS', models.CharField(max_length=50)),
                ('PACKAGE_LOCATION', models.CharField(max_length=50)),
            ],
        ),
    ]
