# Generated by Django 4.1.1 on 2022-10-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CREATE_TRACKING',
            new_name='TRACKING',
        ),
    ]
