# Generated by Django 4.1.1 on 2022-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_create_tracking_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField()),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
    ]
