# Generated by Django 4.1.1 on 2022-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=50000),
        ),
    ]
